# -*- coding: utf-8 -*-
"""Teste exs lista c

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X-NGCIc2BHyv9C-wWadzjnzaP9Z_bZyz
"""

n = int(input("Digite um numero natural: \n"))
soma = 0

for i in range(1,n+1):
   soma = soma +1/i


print(soma)