# -*- coding: utf-8 -*-
"""testeCexs

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ao3qAGq62ar8yG5F8A8nblOLfM08n2gw
"""

"""Exemplo (execício) 7:
Achar a soma dos números inteiros impares no intervalo de 0 a 
100"""

cont = 1
somatorio = 0

while cont<100:
  somatorio +=cont
  cont+=2
  
print(somatorio)

"Achar a primeira potência de 2 maior do que 1000"

dois = 2
produto = 1

while produto<1000:
  produto = produto *dois


print(produto)

"Imprimir os números de 0 a 10."

num = 0
while num<=10:
  print(num)
  num+=1